### ISSUE TITLE
is chrome os supported on nvidia?

### ISSUE THREAD

**Issue by kingmaj0r** [sebanc/brunch#1115]
Title

**Comment by princepjamie06832** [comment]
There's no NVIDIA support for Chrome OS. Only supported for Intel iGPU and AMD APU.

**Comment by UmashankarTriforce** [comment]
Well it's complicated. You can install chrome os on a device if you got an NVIDIA dGPU. But don't expect the display to work from the dGPU as chrome os does not have the drivers for NVIDIA dGPU. If it's like a laptop with an iGPU and an NVIDIA dGPU, you can install chrome os, and disable the dGPU with some kernel parameters. You can also use the NVIDIA dGPU on CUDA compute mode, by using [Brioche](https://github.com/sebanc/brioche) and install the drivers. Since there's no display server attached to the dGPU, don't expect any 3D applications to run on dGPU.

**Comment by lucasgabrielmoreno** [comment]
Yes, Geforce Now:
https://www.nvidia.com/es-ar/geforce-now/

It's still in beta for Chrome OS

**Comment by trusktr** [comment]
> Yes, Geforce Now:

I believe this thread is about installing Chrome OS on a device that has an Nvidia GPU.

Geforce Now is **_not_** Chrome OS running on a computer with an Nvidia CPU. [Geforce Now](https://geforcenow.com) is a service owned by Nvidia that streams application graphics over the network to your system, exactly like [Google Stadia](https://stadia.google.com/). This is why you can run Geforce Now on _**any**_ device simply by [loading Geforce Now inside your browser](https://play.geforcenow.com/) in your browser tab on any device, which is a lot different than Chrome OS on a laptop with Nvidia GPU.
