### ISSUE TITLE
Booting error

### ISSUE THREAD

**Issue by JamieHoogs** [sebanc/brunch#1637]
After I complete the dualboot instructions I try selecting Chromeos in grub but it returns:
 error: no such module.
 error: no such device: /chromeos.img.
 error file `/chromeos.img' not found.
 error: unrecognized number.
 error: disk `loop,7' not found.
 error: you need to load the kernel first.

**Comment by darethehair** [comment]
Strangely, I am now noticing the same problem, even though I have successfully dual-booted for a long time now.  I typed some of the initial Brunch grub lines directly to see what was wrong, and (in my case) these result in '/chromeos.img' not being found:

```
        img_path="/chromeos.img"
        img_uuid="047b8a1c-577c-490c-89e0-b03be254d176"
        search --no-floppy --set=root --file $img_path
```
Because of this, the reset of the grub script fails.
