### ISSUE TITLE
I can't go to the site with network error 118 in brunch

### ISSUE THREAD

**Issue by burnsboyamazing** [sebanc/brunch#2012]
I tried to go to webcompat.com (see also https://github.com/burnsboyamazing/bugs/issues/2) and violetfrost.github.io (see also https://github.com/violetfrost/violetfrost.github.io/issues/60) with network error 118 in ChromeOS but I can't, see @windowz414 for you cannot go to webcompat.com and violetfrost.github.io because it's refusing to go through Github, (webcompat.com, violetfrost.github.io (redirects to violetfrost.net)).
![Screenshot 2024-02-03 11 43 52 AM](https://github.com/sebanc/brunch/assets/154830140/5e1be98d-bb1e-4991-8a1f-87d575588365)
[Screen recording 2024-02-03 11.41.41 AM.webm](https://github.com/sebanc/brunch/assets/154830140/76aaff3d-684a-4fc2-81ef-da8a4d6cfaf7)
![Screenshot 2024-02-03 11 46 20 AM](https://github.com/sebanc/brunch/assets/154830140/31975964-616e-4019-96c0-5c4779d000d7)
[Screen recording 2024-02-03 11.44.04 AM.webm](https://github.com/sebanc/brunch/assets/154830140/a4e4d9d8-1220-4fb5-91be-4426016c8813)

**Comment by windowz414** [comment]
Stop pinging me in every single issue you create here, I swear to God!

The former is because of your network connection, contact your ISP for this.

The latter is because of website is most probably causing a deadlock on GitHub Pages, contact violetfrost for that.

So this is YET ANOTHER ISSUE UNRELATED TO BRUNCH! Now I ask you to STOP PINGING ME IN EVERY SINGLE ISSUE YOU CREATE HERE! If do it one more time, I'm going to seek for assistance from sebanc to take the required measures. YOU HAVE BEEN WARNED FOR THE SECOND TIME!
