### ISSUE TITLE
Rebuilding RootFS causes system damage if ARC++ rooted

### ISSUE THREAD

**Issue by khanhtranngoccva** [sebanc/brunch#301]
The root is lost, because arcpolicy and symlink and other changes are lost.I cannot reroot the system. If I try to root, I will have to restore ARC++ image. I have to powerwash to restore the root ability.
Suggestion: try to implement Magisk systemless root at boot?

**Comment by sebanc** [comment]
Hi,

It would be too complicated/unstable to add android root feature directly in brunch.

The fact that you cannot reinstall andoid root after the rootfs has been rebuilt (reset to default) is an issue with arob (probably due to the installer not checking for a previous install on data partition). Could you create your issue on arob github instead ?
