### ISSUE TITLE
does brunch have the dptf drivers integrated?

### ISSUE THREAD

**Issue by djgerman10** [sebanc/brunch#318]
Intel(R) Dynamic Platform and Thermal Framework Driver

if you don't have it please could you integrate it thanks
[https://github.com/intel/dptf/releases](https://github.com/intel/dptf/releases)

**Comment by sebanc** [comment]
Hi,

I had issues with intel DPTF driver preventing some laptops to boot chromeos in the past so I disabled it in the kernel. Since then a lot of things changed in brunch so I enabled it again in the test build there:
https://github.com/sebanc/brunch-testing/releases

However, if the intel DPTF issues come back, I will have to revert it.

**Comment by djgerman10** [comment]
Thanks a lot!
