### ISSUE TITLE
ChromeOS is very laggy

### ISSUE THREAD

**Issue by desmondam** [sebanc/brunch#329]
I installed ChromeOS by brunching but it is very laggy. Can't do anything smoothly.

**Comment by dkay0670** [comment]
What GPU do you have?

**Comment by desmondam** [comment]
Intel® HD Graphics for Intel Atom® Processor Z3700 Series

**Comment by sebanc** [comment]
If I understand well, you were running chromeos from a usb flashdrive which is expected to be slow unless you have a usb 3.0 ssd flashdrive.

Nevertheless, adding "intel_idle.max_cstate=1" to the kernel command line seems to help improving performance on atom processors.

**Comment by desmondam** [comment]
Ya after installing on hdd its better.still its not smooth sometmes

**Comment by sebanc** [comment]
Ok I am not sure what your cpu is due to your 2 last comments, globally:
- if it is "Atom® Processor Z3700 Series", add "intel_idle.max_cstate=1 enforce_hyperthreading=1" to the kernel command line to have max performance.
- If it is "Celeron N2820", just add "enforce_hyperthreading=1" to have max performance.

If the performance is still not as good as you would expect, you can try other recovery images (notably reef or fizz) and see if it helps.

As far as I know, aside from that there is not much to be done to improve performance on those devices.

**Comment by desmondam** [comment]
Thanks for your reply. But i don't know where to add this line. Can you please help me.

**Comment by hbarsaiyan** [comment]
@desmondam refer to this https://youtu.be/db4Xo_xPTR4 and instead of 
```
enable_updates
```
add the required options

**Comment by desmondam** [comment]
Thank you very much @hbarsaiyan
