### ISSUE TITLE
[Driver fix] Possible idea fix for adding support for AMD A4 5000

### ISSUE THREAD

**Issue by WindowsXP95** [sebanc/brunch#347]
Hey @sebanc i gave FydeOS and Cloudready and they worked fine with my Lenovo Thinkpad x140e. I was wondering if we could import some kernel modules for the AMD A4 5000 from those kernels.

**Comment by sebanc** [comment]
Hi,

The issue is not kernel module, Google builds it's official devices images with additional CPU instructions to improve performance whereas FydeOS and chromiumos build the OS from source without those for best compatibility.

As brunch uses official chromeos images as a base, there needs to be an official chromeos image compatible with your devices CPU.

**Comment by WindowsXP95** [comment]
oh ok thanks
