### ISSUE TITLE
Warnings when creating image file on windows.

### ISSUE THREAD

**Issue by patr-tam** [sebanc/brunch#53]
I get these warnings when I run the command to create the image file: 
"Creating image file
0+0 records in
0+0 records out
0 bytes copied, 0.0007375 s, 0.0 kB/s
WARNING: Primary GPT header is invalid
WARNING: Secondary GPT header is invalid"
It proceeds to create after this but takes a minute or two to move on.

**Comment by sebanc** [comment]
Hi,

The installer is actually creating a 14GB image file and the partition table while those warnings are issued so it is normal that it takes a bit of time.
I think it takes a bit longer on windows than on linux due to the compatibility layer between WSL and windows but unfortunately that's not something I have leverage on.

I am sorry to say there is nothing I can do about this.

I am therefore closing the issue but if you have ideas to improve it, don't hesitate to re-open it.
