### ISSUE TITLE
"rmod tpm" in grub

### ISSUE THREAD

**Issue by jhedfors** [sebanc/brunch#589]
I see that there is a new line "rmod tpm" that is added to the grub menu stanza that is presented at the completion of a fresh install. For me, with the inclusion of that line, I get an error when booting "unknown command rmod" before continuing.  What is this supposed to do?

**Comment by sebanc** [comment]
most users dualboot using ubuntu / linux mint grub, however it suffers for more than 1 year of a known issue which prevents using loop devices unless "rmmod tpm" is set.

Therefore, that line was added by default due to the important number of issues related to this but you can safely remove that line if you don't need it.

**Comment by jhedfors** [comment]
Thank you. After removing it, I no longer get the "unknown command" error for rmod and tpm, and boots normally.

**Comment by jhedfors** [comment]
@sebanc After re-reading your comments, I am wondering is the command supposed to be "rmmod tpm" instead of "rmod tpm"? Maybe there is a typo in the script?

**Comment by sebanc** [comment]
Which grub are you using ? is it the one from brunch or another one like arch linux... ?
