### ISSUE TITLE
Question: What is the difference between project brunch and project croissant?

### ISSUE THREAD

**Issue by NSbuilder** [sebanc/brunch#59]
I notice that there are difference in that brunch doesn't require you to supply a chromium img. nor a tpm emulator. What's different? Also, I understand that project croissant doesn't provide ota updates because it isn't really possible when you combine different images and recovery files. Can I get updates using this?
( except faster development from your side - awesome! )

Btw, I'm currently running Cloudready which is good but doesn't have google play.

So I'm looking for similar experience ( Stability and nice hardware support + OTA updates ) but with Android apps ( and maybe android safety-net, but that's a bonus ). I have a Lenovo y510p. Will I have better luck if I try to use a lenovo chromebook img? Or maybe it doesn't really matter and I should use rummus?

**Comment by sebanc** [comment]
Hi,

While reading this answer please keep in mind that I don't know croissant very well (i was not a croissant user, it just inspired me when I saw what the script was doing).

As far as I know, Croissant: 
- Add ChromiumOS kernel and firmwares to chromeos recovery images.
- Has an update system (command line based ?)
- Has a dual boot system (based on fydeos system ?)

Why I created brunch:
- I needed my own kernel (initially to support surface devices as i have a Surface Pro 5 and Surface Go which require specific patches)
- I wanted to replicate more closely the chromeos standard mechanisms (updates notably) which is done through an initramfs.
- I thought about a different dual boot system.

swtpm generally works the same, croissant uses a pre-compiled binary, it is build from source with brunch.

All in all, depending on your hardware you might have better results with croissant or brunch as it depends on the kernel config and firmwares.

Regarding images, brunch replaces most core components of recovery images with its own so there in the end there are not many differences between images and rammus seems to work fine for most.

Lastly, even though brunch can apply updates using chromeos standard method, I cannot guarantee that at some point it will not break your install (which is why it is disabled by default).
